### ISSUE TITLE
Add LED status lights to robot

### ISSUE THREAD

**Issue by BenBernardCIS** [frc5687/2020-robot#54]
This includes the following color indicators:
Red: control panel detected
Purple: intake deployed and running
White: hopper full
Blue: default
Yellow: targeting but not ready to shoot
Green: ready to shoot

**Comment by SpencerDoughty** [comment]
Red: control panel detected
Green: ready to shoot
Yellow: targeting but not ready to shoot
Purple: intake deployed and running
White: hopper full
Blue: default
